# -*- coding: utf-8 -*-
"""test_desconto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jswnOpMpqCdLtrKLr2wkJiJt30jCEZ8u
"""

import unittest

from desconto import (
    CalculadoraDesconto,
    SemDesconto,
    DescontoPercentual,
    DescontoCupom
)


class TestCalculadoraDesconto(unittest.TestCase):

    def test_sem_desconto_retorna_valor_original(self):
        calculadora = CalculadoraDesconto(SemDesconto())

        valor_final = calculadora.calcular(100)

        self.assertEqual(valor_final, 100)

    def test_desconto_percentual(self):
        calculadora = CalculadoraDesconto(DescontoPercentual(10))

        valor_final = calculadora.calcular(100)

        self.assertEqual(valor_final, 90)

    def test_desconto_por_cupom(self):
        calculadora = CalculadoraDesconto(DescontoCupom(20))

        valor_final = calculadora.calcular(100)

        self.assertEqual(valor_final, 80)

    def test_desconto_por_cupom_nao_deixa_valor_negativo(self):
        calculadora = CalculadoraDesconto(DescontoCupom(150))

        valor_final = calculadora.calcular(100)

        self.assertEqual(valor_final, 0)


if __name__ == "__main__":
    unittest.main()

!python -m unittest test_desconto.py